In [1]:
import tensorflow as tf
tf.__version__

'2.7.0'

### Other kinds of tensors

In [2]:
# Create a tensor of all ones

In [3]:
tf.ones([3,2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeroes

tf.zeros(shape=(3,2))

In [10]:
# X = tf.constant(some_matrix) - Upper case for tensor or matrix
# y = tf.constant(vector) - Lower case for a vector

##Turn NumPy arrays into tensors

The main differernce between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [7]:
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32)

In [8]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [11]:
A = tf.constant(numpy_A)

In [13]:
A = tf.constant(numpy_A, shape = (2,3,4))
B = tf.constant(numpy_A)

In [14]:
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [16]:
# Reshape
C = tf.constant(numpy_A, shape =(3,8))
C

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>