In [44]:
import tensorflow as tf
print (tf.__version__)

2.7.0


### Create a Tensor

In [45]:
non_shuffled_tensor = tf.constant([[1,2], [2,3], [3,4], [4,5], [5,6], [6,7], [7,8]])

In [46]:
non_shuffled_tensor.ndim

2

In [47]:
non_shuffled_tensor.shape

TensorShape([7, 2])

#### Shuffle without seed

In [48]:
tf.random.shuffle(non_shuffled_tensor)

<tf.Tensor: shape=(7, 2), dtype=int32, numpy=
array([[3, 4],
       [2, 3],
       [5, 6],
       [4, 5],
       [7, 8],
       [6, 7],
       [1, 2]], dtype=int32)>

In [49]:
tf.random.shuffle(non_shuffled_tensor)

<tf.Tensor: shape=(7, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [6, 7],
       [7, 8],
       [5, 6],
       [1, 2],
       [3, 4]], dtype=int32)>

Set Operational Level seed

In [50]:
tf.random.shuffle(non_shuffled_tensor, seed=5)

<tf.Tensor: shape=(7, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4],
       [2, 3],
       [7, 8],
       [6, 7],
       [4, 5]], dtype=int32)>

In [51]:
tf.random.shuffle(non_shuffled_tensor, seed=5)

<tf.Tensor: shape=(7, 2), dtype=int32, numpy=
array([[7, 8],
       [3, 4],
       [1, 2],
       [4, 5],
       [6, 7],
       [5, 6],
       [2, 3]], dtype=int32)>

#### Set Global Seed

In [52]:
tf.random.set_seed(25)

In [53]:
tf.random.shuffle(non_shuffled_tensor, seed=5)

<tf.Tensor: shape=(7, 2), dtype=int32, numpy=
array([[7, 8],
       [1, 2],
       [5, 6],
       [3, 4],
       [4, 5],
       [6, 7],
       [2, 3]], dtype=int32)>

In [54]:
tf.random.set_seed(25)
tf.random.shuffle(non_shuffled_tensor, seed=5)

<tf.Tensor: shape=(7, 2), dtype=int32, numpy=
array([[7, 8],
       [1, 2],
       [5, 6],
       [3, 4],
       [4, 5],
       [6, 7],
       [2, 3]], dtype=int32)>

In [55]:
tf.random.set_seed(25)
tf.random.shuffle(non_shuffled_tensor, seed=5)

<tf.Tensor: shape=(7, 2), dtype=int32, numpy=
array([[7, 8],
       [1, 2],
       [5, 6],
       [3, 4],
       [4, 5],
       [6, 7],
       [2, 3]], dtype=int32)>

In [56]:
tf.random.shuffle(non_shuffled_tensor, seed=5)

<tf.Tensor: shape=(7, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4],
       [2, 3],
       [7, 8],
       [6, 7],
       [4, 5]], dtype=int32)>

### Conclusion: To get the same shuffled order, both the global and operational level seed has to be set