In [1]:
import tensorflow as tf
tf.__version__

'2.7.0'

In [3]:
rank_4_tensor = tf.zeros(shape = [2,3,4,5])

### Indexing Tensors


In [5]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2, :2, :2 ]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [8]:
some_list= [1,2,3,4,5]
some_list[:1]

[1]

In [12]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [9]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [11]:
# Get the first element from each dimension from each index except for the second last one
# : - will fetch the whole dimension
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [24]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor= tf.constant([[1,2], [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim


(TensorShape([2, 2]), 2)

In [25]:
# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [26]:
# Add in extra dimension to rank_2_tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [27]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1)  # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [29]:
tf.expand_dims(rank_2_tensor, axis = 0) # Expand 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>