In [1]:
import tensorflow as tf
tf.__version__

'2.7.0'

### Manipulating tensors

**Basic Operations**

'+', '-'

In [4]:
# Add values to a tensor using the addition operator
tensor = tf.constant([[1,2], 
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [5]:
tensor - 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1,  0],
       [ 1,  2]], dtype=int32)>

In [6]:
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [8]:
tf.math.multiply(tensor,  3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  6],
       [ 9, 12]], dtype=int32)>