In [1]:
import tensorflow as tf
tf.__version__

'2.7.0'

In [4]:
# Matrix Multiplication in TensorFlow
tensor = tf.constant([[1,2], [3,4]])
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [5]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [6]:
#Matrix multiplication in python
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [10]:
#Create a tensor (3 , 2)
X= tf.constant([[1,2], [3,4], [5,6]])

#Create another tensor (3 , 2)
y = tf.constant([[7,8], [9,10], [11,12]])

In [12]:
# The tensors X and y cannot be multiplied
# Reshape Y
tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [14]:
X @ tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [16]:
#Transpose a matrix
tf.matmul(tf.transpose(X), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>